# User settings

# Copied from default_settings and modified to avoid changing the defaults

auto_update = true  # Check for updates to remote repo and automatically pull
gzip_output = false # If false save uncompressed .csv files, if true save compressed .csv.gz files

betfair_data = false # Get Betfair data

[fields]

[fields.race_info]
date = true           # Date of race
region = false        # Region of race
course_id = false     # RP Course ID
course = true         # Course name
course_detail = false # Course details

race_id = false   # RP race ID
off = true        # Race off time
race_name = false # Race name

type = false      # Type of racing (Flat/Hurdle/Chase etc)
class = false     # Race class
pattern = false   # Race Pattern (Group 1 etc)

rating_band = false # Rating restrictions
age_band = false    # Age restrictions
sex_rest = false    # Sex restrictions

dist = false    # Distance in miles/furlongs/yards
dist_f = false  # Distance in furlongs
dist_m = false  # Distance in metres
dist_y = false  # Distance in yards

going = false   # Going description
surface = false # Surface Turf/Dirt/AW

ran = false # Number of runners in race

[fields.runner_info]
num = false  # Racecard number
pos = true   # Finishing position
draw = false # Stall number

ovr_btn = false  # Total number of lengths beaten
btn = false      # Lengths behind nearest horse in front

horse_id = false # RP Horse ID
horse = true     # Name of horse
age = false      # Age of horse
sex = false      # Sex of horse

wgt = false # Weight in stones/pounds
lbs = false # Weight in pounds

hg = false  # Headgear

time = false # Time in minutes/seconds
secs = false # Time in seconds

sp = true   # fractional odds
dec = false # decimal odds

jockey_id = false  # RP Jockey ID
jockey = false     # Jockey name
trainer_id = false # RP Trainer ID
trainer = false    # Trainer name

prize = false # Prizemoney

or = false  # Official rating
rpr = false # RP Rating
ts = false  # TS rating

sire_id = false    # RP Sire ID
sire = false       # Sire name
dam_id = false     # RP Dam ID
dam = false        # Dam name
damsire_id = false # RP Damsire ID
damsire = false    # Damsire name

owner_id = false # RP Owner ID
owner = false    # Owner name
silk_url = false # Url of owners silks image

comment = false  # Form in running comments

[fields.betfair]
bsp = true          # Betfair Starting Price
wap = false         # Weighted Average Price
morning_wap = false # Weighted Average Price before 11am
pre_min = true      # Minimum price placed before the off
pre_max = true      # Maximum price placed before the off
ip_min = true       # Minimum price placed in-play
ip_max = true       # Maximum price placed in-play
morning_vol = false # Amount traded before 11am
pre_vol = true      # Amount traded before the off
ip_vol = true       # Amount traded in-play
